In [1]:
import sys; sys.path.insert(0,'..')
from lltk.imports import *
from lltk.model.booknlp import *
setup_log(to_screen=False)

In [2]:
t=Text(CLAR_ID)
tx=t.letters.texts()[0]
tx2=t.letters.t
mt,mtx,mtx2=t.booknlp,tx.booknlp,tx2.booknlp

In [3]:
# mtx.path_data_tokens, mtx.path_data_chars

In [10]:
mt.tokens(force=False)

Iterating models: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 625/625 [00:01<00:00, 482.58it/s]

                 para_i  sent_i  sent_token_i token lemma  onset offset  \
text_id token_i
L001a   0             0       0             0  Miss  Miss      0      4
        1             0       0             1  Anna  Anna      5      9
        2             0       0             2  Howe  Howe     10     14
        3             0       0             3     ,     ,     14     15
        4             0       0             4    To    to     16     18
...                 ...     ...           ...   ...   ...    ...    ...
L527a   1506         28      65            23    J.    J.   6959   6961
        1507         28      65            24    De    De   6962   6964
        1508         28      65            25    la    la   6965   6967
        1509         28      65            26  Tour  Tour   6968   6972
        1510         28      65            27     .     .   6972   6973

                   pos pos2    deprel  ... event   supersense  \
text_id token_i                        ...
L001a   0        PROPN  NNP  compound  ...     O  noun.person
        1        PROPN  NNP  compound  ...     O  noun.person
        2        PROPN  NNP      ROOT  ...     O  noun.person
        3        PUNCT    ,     punct  ...     O
        4          ADP   IN      prep  ...     O
...                ...  ...       ...  ...   ...          ...
L527a   1506     PROPN  NNP  compound  ...     O  noun.person
        1507     PROPN  NNP  compound  ...     O  noun.person
        1508     PROPN  NNP  compound  ...     O  noun.person
        1509     PROPN  NNP     appos  ...     O  noun.person
        1510     PUNCT    .     punct  ...     O

                char_id_mentioned char_id        char_tok char_id_patient  \
text_id token_i
L001a   0                     C01     C01  Miss Anna Howe
        1                     C01     C01  Miss Anna Howe
        2                     C01     C01  Miss Anna Howe
        3
        4
...                           ...     ...             ...             ...
L527a   1506                  C04     C04   F. J. De Tour
        1507                  C04     C04   F. J. De Tour
        1508                  C04     C04   F. J. De Tour
        1509                  C04     C04   F. J. De Tour
        1510

                char_id_agent char_id_poss char_id_speaking_mentioned  \
text_id token_i
L001a   0
        1
        2
        3
        4
...                       ...          ...                        ...
L527a   1506
        1507
        1508
        1509
        1510

                char_id_speaking
text_id token_i
L001a   0
        1
        2
        3
        4
...                          ...
L527a   1506
        1507
        1508
        1509
        1510

[1032039 rows x 21 columns]

In [11]:
mt.chardata()

,text_id,char_i,char_tok,char_toks,char_tok_proper,char_tok_common,char_tok_pronoun,token_i_agent,token_i_patient,token_i_poss,char_pronouns,char_pronouns_inference,count
char_id,,,,,,,,,,,,,
C05,L001a,5,Mr. Lovelace,"[(Mr. Lovelace, 5)]","[(Mr. Lovelace, 5)]",[],"[(his, 7), (him, 3), (he, 2), (me, 1), (I, 1),...","[(240, went), (253, express), (269, avoid), (3...","[(235, gave), (283, left), (365, lay), (864, i...","[(255, concern), (272, sword), (295, power), (...",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",20
C07,L001a,7,Mr. Harlowe,"[(Mr. Harlowe, 1)]","[(Mr. Harlowe, 1)]",[],"[(your, 2), (Your, 1), (you, 1), (You, 1)]","[(326, puts), (334, give)]","[(326, puts)]","[(325, violence), (331, defence), (342, sister)]",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",6
C01,L001a,1,Miss Anna Howe,"[(Miss Anna Howe, 1), (Anna Howe, 1)]","[(Miss Anna Howe, 1), (Anna Howe, 1)]",[],[],[],"[(1195, ranked)]",[],she/her,"{'he/him/his': 0.136, 'she/her': 0.808, 'they/...",2
C12,L002a,12,Arabella,"[(Arabella, 1), (Bella, 1)]","[(Arabella, 1), (Bella, 1)]",[],"[(her, 18), (she, 11), (herself, 3), (hers, 2)...","[(1615, spoken), (1648, began), (1656, compare...",[],"[(1701, uncle), (1734, uncle), (1814, mamma), ...",she/her,"{'he/him/his': 0.087, 'she/her': 0.837, 'they/...",37
C09,L002a,9,Mr. Lovelace,"[(Mr. Lovelace, 9)]","[(Mr. Lovelace, 9)]",[],"[(he, 12), (his, 8), (He, 2), (him, 2)]","[(518, paid), (1264, improving), (1303, has), ...","[(635, introduced)]","[(452, address), (520, respects), (1259, advan...",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
C15,L527a,15,Mr. Lovelace,"[(Mr. Lovelace, 2)]","[(Mr. Lovelace, 2)]",[],"[(he, 1), (his, 1)]","[(816, said), (955, rode)]",[],"[(938, hand), (972, wounds)]",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",4
C13,L527a,13,God,"[(God, 3)]","[(God, 3)]",[],[],[],"[(1420, pray)]",[],he/him/his,"{'he/him/his': 0.59, 'she/her': 0.194, 'they/t...",3
C04,L527a,4,F. J. De Tour,"[(F. J. De la Tour, 2)]","[(F. J. De la Tour, 2)]",[],[],[],[],[],he/him/his,"{'he/him/his': 0.2, 'she/her': 0.2, 'they/them...",2
C11,L527a,11,Clarissa,"[(Clarissa, 2)]","[(Clarissa, 2)]",[],[],[],[],[],she/her,"{'he/him/his': 0.143, 'she/her': 0.74, 'they/t...",2
C96,L527a,96,Ah Monsieur,"[(Ah Monsieur, 1)]","[(Ah Monsieur, 1)]",[],"[(you, 1)]",[],[],[],,{},2

## Character-level data

In [3]:
# mtx.chardata()
mtx.chardata()

,text_id,char_i,char_tok,char_toks,char_tok_proper,char_tok_common,char_tok_pronoun,token_i_agent,token_i_patient,token_i_poss,char_pronouns,char_pronouns_inference,count
char_id,,,,,,,,,,,,,
C05,L001a,5,Mr. Lovelace,"[(Mr. Lovelace, 5)]","[(Mr. Lovelace, 5)]",[],"[(his, 7), (him, 3), (he, 2), (me, 1), (I, 1),...","[(240, went), (253, express), (269, avoid), (3...","[(235, gave), (283, left), (365, lay), (864, i...","[(255, concern), (272, sword), (295, power), (...",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",20
C07,L001a,7,Mr. Harlowe,"[(Mr. Harlowe, 1)]","[(Mr. Harlowe, 1)]",[],"[(your, 2), (Your, 1), (you, 1), (You, 1)]","[(326, puts), (334, give)]","[(326, puts)]","[(325, violence), (331, defence), (342, sister)]",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",6
C01,L001a,1,Miss Anna Howe,"[(Miss Anna Howe, 1), (Anna Howe, 1)]","[(Miss Anna Howe, 1), (Anna Howe, 1)]",[],[],[],"[(1195, ranked)]",[],she/her,"{'he/him/his': 0.136, 'she/her': 0.808, 'they/...",2

In [4]:
mtx.chardata(allow_empty=True).sort_values('char_id').head()

,text_id,char_i,char_tok,char_toks,char_tok_proper,char_tok_common,char_tok_pronoun,token_i_agent,token_i_patient,token_i_poss,char_pronouns,char_pronouns_inference,count
char_id,,,,,,,,,,,,,
C01,L001a,1,Miss Anna Howe,"[(Miss Anna Howe, 1), (Anna Howe, 1)]","[(Miss Anna Howe, 1), (Anna Howe, 1)]",[],[],[],"[(1195, ranked)]",[],she/her,"{'he/him/his': 0.136, 'she/her': 0.808, 'they/...",2
C05,L001a,5,Mr. Lovelace,"[(Mr. Lovelace, 5)]","[(Mr. Lovelace, 5)]",[],"[(his, 7), (him, 3), (he, 2), (me, 1), (I, 1),...","[(240, went), (253, express), (269, avoid), (3...","[(235, gave), (283, left), (365, lay), (864, i...","[(255, concern), (272, sword), (295, power), (...",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",20
C07,L001a,7,Mr. Harlowe,"[(Mr. Harlowe, 1)]","[(Mr. Harlowe, 1)]",[],"[(your, 2), (Your, 1), (you, 1), (You, 1)]","[(326, puts), (334, give)]","[(326, puts)]","[(325, violence), (331, defence), (342, sister)]",he/him/his,"{'he/him/his': 0.811, 'she/her': 0.113, 'they/...",6
C11,L001a,11,,[],[],[],"[(your, 5), (you, 3), (yourself, 1)]","[(105, receive), (112, help)]","[(36, hurt)]","[(29, family), (152, sake), (156, brother), (2...",,{},9
C12,L001a,12,,[],[],"[(your family, 3)]","[(they, 1)]","[(235, gave)]","[(228, blame)]",[],they/them/their,"{'he/him/his': 0, 'she/her': 0, 'they/them/the...",4

## Token-level data

### Entities

In [5]:
mtx.entities()

,COREF,start_token,end_token,prop,cat,text,text_id,char_i,char_id
0,1,0,2,PROP,PER,Miss Anna Howe,L001a,1,C01
1,2,5,7,PROP,PER,Miss Clarissa Harlowe,L001a,2,C02
2,0,12,12,PRON,PER,I,L001a,0,C00
3,0,17,17,PRON,PER,my,L001a,0,C00
4,10,17,19,NOM,PER,my dearest friend,L001a,10,C10
...,...,...,...,...,...,...,...,...,...
212,49,1270,1270,PRON,PER,you,L001a,49,C49
213,68,1273,1273,PRON,PER,she,L001a,68,C68
214,49,1279,1279,PRON,PER,you,L001a,49,C49
215,68,1284,1284,PRON,PER,she,L001a,68,C68
216,69,1286,1286,PRON,PER,his,L001a,69,C69

### Supersenses

In [6]:
mtx.supersenses()

     start_token  end_token supersense_category                   text text_id
0              0          2         noun.person         Miss Anna Howe   L001a
1              5          7         noun.person  Miss Clarissa Harlowe   L001a
2              9         10         noun.person                Jan. 10   L001a
3             13         13        verb.stative                     am   L001a
4             19         19         noun.person                 friend   L001a
..           ...        ...                 ...                    ...     ...
339         1277       1277        noun.feeling             preference   L001a
340         1278       1278     verb.possession                  given   L001a
341         1285       1285      verb.cognition                  knows   L001a
342         1287       1287         noun.motive                reasons   L001a
343         1290       1290        noun.feeling             preference   L001a

[344 rows x 5 columns]

### Quotations

In [7]:
mtx.quotes()

,quote_start,quote_end,mention_start,mention_end,mention_phrase,char_id,quote,text_id,char_i
0,204,260,194,195,Mr. Wyerley,C04,' he is far from being partial to Mr. Lovelace...,L001a,4
1,316,355,313,313,he,C05,"'' Have a care , Mr. Harlowe -- Your violence ...",L001a,5
2,835,841,831,831,his,C48,' the blood of her brother .,L001a,48

### Tokens

Combines three above

In [8]:
mtx.tokens()

                 para_i  sent_i  sent_token_i       token       lemma  onset  \
text_id token_i
L001a   0             0       0             0        Miss        Miss      0
        1             0       0             1        Anna        Anna      5
        2             0       0             2        Howe        Howe     10
        3             0       0             3           ,           ,     14
        4             0       0             4          To          to     16
...                 ...     ...           ...         ...         ...    ...
        1287         16      37            32     reasons      reason   5955
        1288         16      37            33         for         for   5963
        1289         16      37            34        that        that   5967
        1290         16      37            35  preference  preference   5972
        1291         16      37            36           .           .   5982

                 offset    pos pos2    deprel  ...  event    supersense  \
text_id token_i                                ...
L001a   0             4  PROPN  NNP  compound  ...      O   noun.person
        1             9  PROPN  NNP  compound  ...      O   noun.person
        2            14  PROPN  NNP      ROOT  ...      O   noun.person
        3            15  PUNCT    ,     punct  ...      O
        4            18    ADP   IN      prep  ...      O
...                 ...    ...  ...       ...  ...    ...           ...
        1287       5962   NOUN  NNS      dobj  ...      O   noun.motive
        1288       5966    ADP   IN      prep  ...      O
        1289       5971    DET   DT       det  ...      O
        1290       5982   NOUN   NN      pobj  ...      O  noun.feeling
        1291       5983  PUNCT    .     punct  ...      O

                char_id_mentioned char_id        char_tok char_id_patient  \
text_id token_i
L001a   0                     C01     C01  Miss Anna Howe
        1                     C01     C01  Miss Anna Howe
        2                     C01     C01  Miss Anna Howe
        3
        4
...                           ...     ...             ...             ...
        1287
        1288
        1289
        1290
        1291

                char_id_agent char_id_poss char_id_speaking_mentioned  \
text_id token_i
L001a   0
        1
        2
        3
        4
...                       ...          ...                        ...
        1287
        1288
        1289
        1290
        1291

                char_id_speaking
text_id token_i
L001a   0
        1
        2
        3
        4
...                          ...
        1287
        1288
        1289
        1290
        1291

[1292 rows x 21 columns]

## Character IDs

In [9]:
def get_df_names(self,force=False):
    if force or self._df_names is None:
        char_toks=self.get_character_token_counts()
        o_text=[]
        for char_tok,char_tok_count in char_toks.most_common():
            if type(char_tok)!= str or not char_tok: continue
            char_id=zeropunc(char_tok)
            otextd=dict(char_tok=char_tok,char_id=char_id,char_tok_count=char_tok_count,char_tok_i=len(o_text)+1)
            o_text.append(otextd)
        odf_tok2id=pd.DataFrame(o_text).sort_values(
            ['char_tok_count','char_tok_i'],
            ascending=[False,True]
        ).fillna('').set_index('char_tok')
        odf_tok2id['is_valid']=''
        self._df_names=odf_tok2id
        #save_df(odf_tok2id, self.path_names, verbose=False)
        #self._df_names=merge_read_dfs_anno(self.path_names, on='char_tok').fillna('')
    return self._df_names

In [10]:
get_df_names(mt,force=False)

Iterating models:   0%|▎                                                                                                                                                                                                     | 1/625 [00:28<4:51:14, 28.00s/it]

KeyboardInterrupt:

## Interactions

In [ ]:
def interactions(self):
    pass